// GENERATED by scripts/pin_llama.py — do not hand-edit.
//
// Regenerate with:
//   python3 scripts/pin_llama.py > src-tauri/src/llama/llama_pins.rs

pub const LLAMA_BUILD: &str = "b10502";

pub const LLAMA_ASSETS: &[LlamaAsset] = &[
    LlamaAsset {
        target: "macos-arm64",
        archive: Archive::TarGz,
        sha256: "cf7815f8ddedd9af79b5ebd0a4556f74852e5228fe7e61b9be317165983122d5",
        size: 11087640,
    },
    LlamaAsset {
        target: "macos-x64",
        archive: Archive::TarGz,
        sha256: "f9274a88820112699ff0f35a265179e6156dfb202bb005501023f46927feb911",
        size: 11393795,
    },
    LlamaAsset {
        target: "ubuntu-x64",
        archive: Archive::TarGz,
        sha256: "6541314ac6b17b92ddc0fe3b8dd3c66c9b1f0846df74fa0211044244f52519d2",
        size: 16662953,
    },
    LlamaAsset {
        target: "ubuntu-vulkan-x64",
        archive: Archive::TarGz,
        sha256: "f4c22be9b4da822193af79f9f82dcd80d847775df46768aabc48d1dd0f8531f5",
        size: 33273760,
    },
    LlamaAsset {
        target: "ubuntu-arm64",
        archive: Archive::TarGz,
        sha256: "ffecb07ba126a883cd975420f43e24a24909ba57d74f2ba1fc252e9d236b098c",
        size: 13524786,
    },
    LlamaAsset {
        target: "ubuntu-vulkan-arm64",
        archive: Archive::TarGz,
        sha256: "1acdb4031ab241cf512f3955f587852cb6455eeecd11218add592602783bd8c3",
        size: 27248746,
    },
    LlamaAsset {
        target: "win-cpu-x64",
        archive: Archive::Zip,
        sha256: "bf009ffc8a7c0ce8631122668281f1df39c16856efb9270c3de805cf6d4b211f",
        size: 18492526,
    },
    LlamaAsset {
        target: "win-vulkan-x64",
        archive: Archive::Zip,
        sha256: "4353011b6f51e873ea82bc6eb49d39747b0339d5ff17f06245fbf06ebbd26a7b",
        size: 34839264,
    },
    LlamaAsset {
        target: "win-cpu-arm64",
        archive: Archive::Zip,
        sha256: "3175dfeb7e006b15fd9bf41df479dbf6cd3c90b7c3710aa6dae110a6ba042c20",
        size: 12250004,
    },
];
