// GENERATED by scripts/pin_mlx.py — do not hand-edit.
//
// Regenerate with:
//   python3 scripts/pin_mlx.py > src-tauri/src/llama/mlx_pins.rs

pub const MLX_VERSION: &str = "v0.1.1";
pub const MLX_SHA256: &str = "e8d296e46bf9b1bcb7492c1685e8871d35d7b0deb601bd7dc9dd887c9327b089";
pub const MLX_SIZE: u64 = 18857962;
