// GENERATED by scripts/pin_mlx.py — do not hand-edit.
//
// Regenerate with:
//   python3 scripts/pin_mlx.py > src-tauri/src/llama/mlx_pins.rs

pub const MLX_VERSION: &str = "v0.1.5";
pub const MLX_SHA256: &str = "8cdd910f5712d5b806b68421fd3f7a54bdd666c9f19d44ec7c9cef5efbf827b9";
pub const MLX_SIZE: u64 = 20100682;
