// GENERATED by scripts/pin_mtplx.py — do not hand-edit.
//
// Regenerate with:
//   python3 scripts/pin_mtplx.py > src-tauri/src/llama/mtplx_pins.rs

/// The interpreter the MTPLX venv is built on. Bundled rather than borrowed:
/// macOS ships Python 3.9 and MTPLX needs 3.11+, so "use the system python"
/// means "does not install" on any Mac without Homebrew.
pub const PYTHON_VERSION: &str = "3.12.14+20260814";
pub const PYTHON_URL: &str = "https://github.com/astral-sh/python-build-standalone/releases/download/20260814/cpython-3.12.14%2B20260814-aarch64-apple-darwin-install_only.tar.gz";
pub const PYTHON_SHA256: &str = "4572133a5542f306b9bdb155da5800f9e38950cd0a98d469b832ce256fe299ea";
pub const PYTHON_SIZE: u64 = 25151480;

/// The MTPLX release to install into that venv.
pub const MTPLX_VERSION: &str = "2.9.1";
