//! Getting a `llama-server` onto disk.
//!
//! Local inference runs as a **sidecar process**, not as in-process bindings.
//! Compiling llama.cpp ourselves would put a C++/CMake toolchain on all six
//! release targets, break the windows-arm64 cross build, and turn the GPU
//! backend into a build-time decision — one bundle per accelerator. Fetching
//! the upstream `llama-server` keeps the backend a runtime choice and keeps our
//! build matrix exactly as it is.
//!
//! GitHub's release API publishes immutable per-tag asset URLs and a size, but
//! no checksum, so the hashes below are computed by `scripts/pin_llama.py` and
//! committed — same arrangement as the Chromium build in `browser::provision`
//! and the embedding model in `code_intel::embeddings`.

use crate::download::{DEFAULT_RETRIES, ProgressFn, download_verified_with_retries};
use crate::net_activity::NetSource;
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

pub struct LlamaAsset {
    /// The substring between "bin-" and the extension in the asset name, e.g.
    /// "macos-arm64". Also the leaf of the install directory.
    pub target: &'static str,
    pub archive: Archive,
    pub sha256: &'static str,
    pub size: u64,
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Archive {
    TarGz,
    Zip,
}

/// Which upstream build to fetch. Persisted in `LocalPrefs`, so a user whose
/// Vulkan driver breaks can drop to CPU without re-downloading their models.
#[derive(Clone, Copy, PartialEq, Eq, Debug, Default, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Backend {
    #[default]
    Auto,
    Cpu,
    Vulkan,
}

// GENERATED by scripts/pin_llama.py — do not hand-edit.
include!("llama_pins.rs");

const BASE_URL: &str = "https://github.com/ggml-org/llama.cpp/releases/download";

/// Written only after a complete extraction, so a crash mid-unpack can never
/// leave a half-populated directory that looks installed. Contains the build
/// tag, which is what `gc_stale_installs` compares against.
const READY_MARKER: &str = ".ready";

/// Preferred → fallback asset targets for this host, most capable first.
/// Empty on a target upstream does not publish (32-bit, BSD, macOS on nothing).
pub fn host_targets(backend: Backend) -> &'static [&'static str] {
    match (std::env::consts::OS, std::env::consts::ARCH, backend) {
        // Metal is compiled into the macOS builds; there is no separate asset.
        ("macos", "aarch64", _) => &["macos-arm64"],
        ("macos", "x86_64", _) => &["macos-x64"],
        ("linux", "x86_64", Backend::Cpu) => &["ubuntu-x64"],
        ("linux", "x86_64", _) => &["ubuntu-vulkan-x64", "ubuntu-x64"],
        ("linux", "aarch64", Backend::Cpu) => &["ubuntu-arm64"],
        ("linux", "aarch64", _) => &["ubuntu-vulkan-arm64", "ubuntu-arm64"],
        ("windows", "x86_64", Backend::Cpu) => &["win-cpu-x64"],
        ("windows", "x86_64", _) => &["win-vulkan-x64", "win-cpu-x64"],
        ("windows", "aarch64", _) => &["win-cpu-arm64"],
        _ => &[],
    }
}

/// The target actually used for this host: the first pinned candidate, except
/// that `Auto` only takes a Vulkan build when a loader is present. A Vulkan
/// binary without `vulkan-1.dll`/`libvulkan.so.1` exits at startup, and a
/// download that can never run is worse than a slower CPU build.
pub fn resolved_target(backend: Backend) -> Option<&'static str> {
    let candidates = host_targets(backend);
    let skip_vulkan = backend == Backend::Auto && !has_vulkan_loader();
    candidates
        .iter()
        .find(|t| !(skip_vulkan && t.contains("vulkan")))
        .or_else(|| candidates.first())
        .copied()
        .filter(|t| asset_for(t).is_some())
}

pub fn asset_for(target: &str) -> Option<&'static LlamaAsset> {
    LLAMA_ASSETS.iter().find(|a| a.target == target)
}

pub fn artifact_url(build: &str, target: &str) -> Option<String> {
    let asset = asset_for(target)?;
    let ext = match asset.archive {
        Archive::TarGz => "tar.gz",
        Archive::Zip => "zip",
    };
    Some(format!(
        "{BASE_URL}/{build}/llama-{build}-bin-{target}.{ext}"
    ))
}

/// Root for everything this module owns, under the machine-local app data dir.
/// Never inside the workspace: the weights are mmapped, and an mmap over SMB
/// hangs or corrupts — the lesson already recorded for the index database.
pub fn llama_dir() -> Result<PathBuf, String> {
    let base = dirs::data_dir().ok_or_else(|| "no data directory on this platform".to_string())?;
    Ok(base.join("claudinio-code").join("llama"))
}

/// Install directory for one (build, target) pair, e.g. `b10502-macos-arm64`.
///
/// Keyed by both so a pin bump or a backend switch lands in a fresh directory
/// instead of half-overwriting a live one. Deliberately short for the same
/// Windows MAX_PATH reason as `browser::provision::install_dir`.
pub fn install_dir(target: &str) -> Result<PathBuf, String> {
    Ok(llama_dir()?.join(format!("{LLAMA_BUILD}-{target}")))
}

pub fn exe_name() -> &'static str {
    if cfg!(windows) {
        "llama-server.exe"
    } else {
        "llama-server"
    }
}

/// Absolute path of the managed executable, whether or not it exists yet.
pub fn managed_exe(target: &str) -> Result<PathBuf, String> {
    Ok(install_dir(target)?.join(exe_name()))
}

pub fn is_installed(target: &str) -> bool {
    match (install_dir(target), managed_exe(target)) {
        (Ok(dir), Ok(exe)) => dir.join(READY_MARKER).exists() && exe.exists(),
        _ => false,
    }
}

/// Download and unpack the pinned build if it is not already installed.
///
/// Callers must have user consent before reaching here: this spends 11-35 MB of
/// someone's bandwidth, which is not something a tool call may do on its own.
pub async fn ensure_installed(
    backend: Backend,
    on_progress: Option<&ProgressFn>,
) -> Result<PathBuf, String> {
    let target = resolved_target(backend).ok_or_else(|| {
        format!(
            "no llama.cpp build published for {}-{}",
            std::env::consts::OS,
            std::env::consts::ARCH
        )
    })?;
    let exe = managed_exe(target)?;
    if is_installed(target) {
        return Ok(exe);
    }
    let asset = asset_for(target).expect("resolved_target only returns pinned targets");
    let url = artifact_url(LLAMA_BUILD, target).expect("pinned target has a URL");

    let dir = install_dir(target)?;
    // A previous attempt may have died mid-unpack; start clean rather than
    // extracting over the wreckage.
    if dir.exists() {
        std::fs::remove_dir_all(&dir).map_err(|e| format!("clear {}: {e}", dir.display()))?;
    }
    std::fs::create_dir_all(&dir).map_err(|e| format!("create {}: {e}", dir.display()))?;

    let ext = match asset.archive {
        Archive::TarGz => "tar.gz",
        Archive::Zip => "zip",
    };
    let archive_path = llama_dir()?.join(format!("llama-{LLAMA_BUILD}-{target}.{ext}"));
    let label = format!("llama.cpp {LLAMA_BUILD} ({target})");
    download_verified_with_retries(
        &url,
        &archive_path,
        &label,
        asset.sha256,
        asset.size,
        NetSource::LlamaServerDownload,
        on_progress,
        DEFAULT_RETRIES,
    )
    .await?;

    let kind = asset.archive;
    let archive_for_task = archive_path.clone();
    let dir_for_task = dir.clone();
    // Decompressing tens of MB is blocking CPU and file I/O; leaving it on an
    // async worker would stall every other task on the runtime.
    tokio::task::spawn_blocking(move || match kind {
        Archive::TarGz => extract_tar_gz(&archive_for_task, &dir_for_task),
        Archive::Zip => extract_zip(&archive_for_task, &dir_for_task),
    })
    .await
    .map_err(|e| format!("extract task failed: {e}"))??;

    let _ = std::fs::remove_file(&archive_path);

    if !exe.exists() {
        return Err(format!(
            "extracted archive is missing {} at {}",
            exe_name(),
            dir.display()
        ));
    }
    std::fs::write(dir.join(READY_MARKER), LLAMA_BUILD)
        .map_err(|e| format!("write ready marker: {e}"))?;
    Ok(exe)
}

/// Remove every managed install, leaving downloaded models alone.
pub fn uninstall() -> Result<(), String> {
    let dir = llama_dir()?;
    if dir.exists() {
        std::fs::remove_dir_all(&dir).map_err(|e| format!("remove {}: {e}", dir.display()))?;
    }
    Ok(())
}

/// Delete installs from an older pin. Without this every bump leaks a full
/// copy of the runtime, and the user has no way to see it.
/// Whether a directory under `llama_dir()` belongs to a runtime this build
/// still uses.
///
/// Every runtime installed here must be listed. The sweep deletes whatever is
/// not, so an omission is not a leak — it is the app erasing a working install
/// on the next launch, then reporting the runtime as missing. That is exactly
/// what happened to MTPLX: 588 MB removed at startup, and a "not installed"
/// error pointing at a Settings button the user had already pressed.
fn is_current_install(name: &str) -> bool {
    name.starts_with(&format!("{LLAMA_BUILD}-"))
        || name == format!("mlx-{MLX_VERSION}")
        || name == format!("mtplx-{MTPLX_VERSION}")
}

pub fn gc_stale_installs() {
    let Ok(dir) = llama_dir() else { return };
    let Ok(entries) = std::fs::read_dir(&dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
        if !is_current_install(name) {
            let _ = std::fs::remove_dir_all(&path);
        }
    }
}

// GENERATED by scripts/pin_mlx.py — do not hand-edit.
include!("mlx_pins.rs");

// The archive carries a Metal-linked binary plus its shader bundle; a few
// hundred KB would mean the package step shipped the wrong thing. Checked here
// rather than in a test so a bad regenerate cannot compile at all.
const _: () = assert!(MLX_SIZE > 5_000_000);

const MLX_REPO: &str = "claudin-io/claudinio-mlx";
const MLX_ASSET: &str = "claudinio-mlx-macos-arm64.tar.gz";

/// Root of the managed MLX runtime, versioned like the llama.cpp one so a pin
/// bump lands in a fresh directory instead of half-overwriting a live install.
pub fn mlx_install_dir() -> Result<PathBuf, String> {
    Ok(llama_dir()?.join(format!("mlx-{MLX_VERSION}")))
}

/// The MLX sidecar binary.
///
/// It ships beside `mlx-swift_Cmlx.bundle`, which carries the compiled Metal
/// shaders; separated, the binary starts and then dies on the first tensor
/// operation with "Failed to load the default metallib", so both are extracted
/// into this one directory.
pub fn mlx_exe() -> Result<PathBuf, String> {
    Ok(mlx_install_dir()?.join("claudinio-mlx"))
}

pub fn mlx_installed() -> bool {
    match (mlx_install_dir(), mlx_exe()) {
        (Ok(dir), Ok(exe)) => dir.join(READY_MARKER).exists() && exe.is_file(),
        _ => false,
    }
}

pub fn mlx_artifact_url() -> String {
    format!("https://github.com/{MLX_REPO}/releases/download/{MLX_VERSION}/{MLX_ASSET}")
}

pub fn mlx_download_size() -> u64 {
    MLX_SIZE
}

pub fn mlx_version() -> &'static str {
    MLX_VERSION
}

/// Download and unpack the pinned MLX sidecar.
///
/// Ours rather than upstream's, but pinned by sha256 all the same: being our
/// own artifact says nothing about the network it arrives over.
pub async fn ensure_mlx_installed(on_progress: Option<&ProgressFn>) -> Result<PathBuf, String> {
    if !cfg!(all(target_os = "macos", target_arch = "aarch64")) {
        return Err("the MLX engine is Apple Silicon only".into());
    }
    let exe = mlx_exe()?;
    if mlx_installed() {
        return Ok(exe);
    }

    let dir = mlx_install_dir()?;
    if dir.exists() {
        std::fs::remove_dir_all(&dir).map_err(|e| format!("clear {}: {e}", dir.display()))?;
    }
    std::fs::create_dir_all(&dir).map_err(|e| format!("create {}: {e}", dir.display()))?;

    let archive_path = llama_dir()?.join(format!("claudinio-mlx-{MLX_VERSION}.tar.gz"));
    download_verified_with_retries(
        &mlx_artifact_url(),
        &archive_path,
        &format!("claudinio-mlx {MLX_VERSION}"),
        MLX_SHA256,
        MLX_SIZE,
        NetSource::LlamaServerDownload,
        on_progress,
        DEFAULT_RETRIES,
    )
    .await?;

    let archive_for_task = archive_path.clone();
    let dir_for_task = dir.clone();
    tokio::task::spawn_blocking(move || extract_tar_gz(&archive_for_task, &dir_for_task))
        .await
        .map_err(|e| format!("extract task failed: {e}"))??;
    let _ = std::fs::remove_file(&archive_path);

    if !exe.is_file() {
        return Err(format!(
            "extracted archive is missing claudinio-mlx at {}",
            dir.display()
        ));
    }
    // Without the shader bundle the binary starts and dies on first use, which
    // presents as a mystery timeout rather than a missing file.
    if !dir.join("mlx-swift_Cmlx.bundle").exists() {
        return Err("extracted archive is missing the Metal shader bundle".into());
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(&exe, std::fs::Permissions::from_mode(0o755));
    }
    std::fs::write(dir.join(READY_MARKER), MLX_VERSION)
        .map_err(|e| format!("write ready marker: {e}"))?;
    Ok(exe)
}

// ---------------------------------------------------------------- MTPLX ---
//
// The only engine here that is a Python package. Everything below exists to
// make that invisible: the user turns MTPLX on and the app produces a working
// interpreter, a venv and a pinned MTPLX in it, with no Homebrew, no PATH and
// no `pip` of their own involved.

include!("mtplx_pins.rs");

pub fn mtplx_install_dir() -> Result<PathBuf, String> {
    Ok(llama_dir()?.join(format!("mtplx-{MTPLX_VERSION}")))
}

/// The bundled interpreter.
///
/// Directly under the install dir, not under `python/`: the tarball's root is
/// a `python/` directory and `extract_tar_gz` strips the common root — which is
/// what makes llama.cpp's tag directory disappear, and does the same here.
fn mtplx_python(dir: &Path) -> PathBuf {
    dir.join("bin").join("python3")
}

/// The `mtplx` entry point the supervisor runs.
pub fn mtplx_exe() -> Result<PathBuf, String> {
    Ok(mtplx_install_dir()?.join("venv").join("bin").join("mtplx"))
}

pub fn mtplx_installed() -> bool {
    match (mtplx_install_dir(), mtplx_exe()) {
        (Ok(dir), Ok(exe)) => dir.join(READY_MARKER).exists() && exe.is_file(),
        _ => false,
    }
}

pub fn mtplx_version() -> &'static str {
    MTPLX_VERSION
}

/// What the install costs in bandwidth, as far as it can be known up front.
///
/// Only the interpreter has a pinned size; the wheels `pip` then resolves do
/// not, and MLX alone is a large one. Reporting the honest floor and calling it
/// a floor beats a confident number that is wrong by 200 MB.
pub fn mtplx_download_size() -> u64 {
    PYTHON_SIZE
}

/// Build a working MTPLX: unpack the pinned interpreter, make a venv, install
/// the pinned release into it.
///
/// Callers must have user consent before reaching here — this spends a few
/// hundred MB of someone's bandwidth.
pub async fn ensure_mtplx_installed(on_progress: Option<&ProgressFn>) -> Result<PathBuf, String> {
    if !cfg!(all(target_os = "macos", target_arch = "aarch64")) {
        return Err("MTPLX is Apple Silicon only".into());
    }
    let exe = mtplx_exe()?;
    if mtplx_installed() {
        return Ok(exe);
    }

    let dir = mtplx_install_dir()?;
    if dir.exists() {
        std::fs::remove_dir_all(&dir).map_err(|e| format!("clear {}: {e}", dir.display()))?;
    }
    std::fs::create_dir_all(&dir).map_err(|e| format!("create {}: {e}", dir.display()))?;

    let archive = llama_dir()?.join(format!("cpython-{PYTHON_VERSION}.tar.gz"));
    download_verified_with_retries(
        PYTHON_URL,
        &archive,
        &format!("Python {PYTHON_VERSION}"),
        PYTHON_SHA256,
        PYTHON_SIZE,
        NetSource::LlamaServerDownload,
        on_progress,
        DEFAULT_RETRIES,
    )
    .await?;

    let archive_for_task = archive.clone();
    let dir_for_task = dir.clone();
    tokio::task::spawn_blocking(move || extract_tar_gz(&archive_for_task, &dir_for_task))
        .await
        .map_err(|e| format!("extract task failed: {e}"))??;
    let _ = std::fs::remove_file(&archive);

    let python = mtplx_python(&dir);
    if !python.is_file() {
        return Err(format!(
            "the extracted interpreter has no bin/python3 under {}",
            dir.display()
        ));
    }

    run_tool(
        &python,
        &[
            "-m",
            "venv",
            "--copies",
            &dir.join("venv").display().to_string(),
        ],
        "create the MTPLX environment",
    )
    .await?;

    let pip = dir.join("venv").join("bin").join("pip");
    // `--no-input` because a pip that stops to ask something has nobody to ask:
    // this runs with no terminal attached and would hang until the user gave up
    // on the app rather than on the install.
    run_tool(
        &pip,
        &[
            "install",
            "--no-input",
            "--disable-pip-version-check",
            &format!("mtplx[server]=={MTPLX_VERSION}"),
        ],
        "install MTPLX",
    )
    .await?;

    if !exe.is_file() {
        return Err("pip reported success but produced no mtplx executable".into());
    }
    std::fs::write(dir.join(READY_MARKER), MTPLX_VERSION)
        .map_err(|e| format!("write ready marker: {e}"))?;
    Ok(exe)
}

/// Run one step of the install, failing with what it actually printed.
///
/// `pip` and `venv` report their real problem on stderr and exit non-zero with
/// nothing on stdout, so a bare exit code reaches the user as "install failed"
/// and nothing else.
async fn run_tool(exe: &Path, args: &[&str], what: &str) -> Result<(), String> {
    let mut cmd = tokio::process::Command::new(exe);
    cmd.args(args)
        .stdin(std::process::Stdio::null())
        .kill_on_drop(true);
    crate::procutil::no_window_tokio(&mut cmd);
    let out = cmd
        .output()
        .await
        .map_err(|e| format!("could not {what}: {e}"))?;
    if out.status.success() {
        return Ok(());
    }
    let stderr = String::from_utf8_lossy(&out.stderr);
    let tail: Vec<&str> = stderr.lines().rev().take(6).collect();
    let detail: Vec<&str> = tail.into_iter().rev().collect();
    Err(format!("could not {what}: {}", detail.join(" / ")))
}

pub fn mtplx_uninstall() -> Result<(), String> {
    let dir = mtplx_install_dir()?;
    if dir.exists() {
        std::fs::remove_dir_all(&dir).map_err(|e| format!("remove {}: {e}", dir.display()))?;
    }
    Ok(())
}

pub fn mlx_uninstall() -> Result<(), String> {
    let dir = mlx_install_dir()?;
    if dir.exists() {
        std::fs::remove_dir_all(&dir).map_err(|e| format!("remove {}: {e}", dir.display()))?;
    }
    Ok(())
}

/// A `llama-server` the user already has. Offered as an alternative to the
/// download, and the escape hatch when antivirus quarantines ours.
pub fn detect_system_llama_server() -> Option<PathBuf> {
    if let Ok(explicit) = std::env::var("CLAUDINIO_LLAMA_SERVER") {
        let path = PathBuf::from(explicit);
        if path.exists() {
            return Some(path);
        }
    }
    if let Ok(path_var) = std::env::var("PATH") {
        for dir in std::env::split_paths(&path_var) {
            let candidate = dir.join(exe_name());
            if candidate.is_file() {
                return Some(candidate);
            }
        }
    }
    let extra: &[&str] = match std::env::consts::OS {
        "macos" => &[
            "/opt/homebrew/bin/llama-server",
            "/usr/local/bin/llama-server",
        ],
        "linux" => &["/usr/local/bin/llama-server", "/usr/bin/llama-server"],
        _ => &[],
    };
    extra.iter().map(PathBuf::from).find(|p| p.is_file())
}

/// Whether a Vulkan ICD loader is installed. Best-effort and cheap: this only
/// decides which asset to fetch, and `ensure_installed` is never on a hot path.
fn has_vulkan_loader() -> bool {
    match std::env::consts::OS {
        "windows" => {
            if let Ok(root) = std::env::var("SystemRoot")
                && Path::new(&root)
                    .join("System32")
                    .join("vulkan-1.dll")
                    .exists()
            {
                return true;
            }
            std::env::var("PATH")
                .is_ok_and(|p| std::env::split_paths(&p).any(|d| d.join("vulkan-1.dll").is_file()))
        }
        "linux" => [
            "/usr/lib/x86_64-linux-gnu/libvulkan.so.1",
            "/usr/lib/aarch64-linux-gnu/libvulkan.so.1",
            "/usr/lib64/libvulkan.so.1",
            "/usr/lib/libvulkan.so.1",
            "/lib/x86_64-linux-gnu/libvulkan.so.1",
        ]
        .iter()
        .any(|p| Path::new(p).exists()),
        // Metal is built in; there is no Vulkan asset to choose on macOS.
        _ => false,
    }
}

/// The single top-level directory every entry shares, if there is one.
///
/// The macOS/Linux tarballs are built with `tar --transform "s,^\.,llama-<tag>,"`
/// and so nest everything one level deep, while the Windows zips are flat.
/// Flattening that away means the executable is always at `install_dir()/llama-server`
/// regardless of tag — and, load-bearing, that `libllama.dylib`/`libggml*.so`
/// stay beside it, since the binary resolves them via `@loader_path`/`$ORIGIN`.
fn common_root(names: &[String]) -> Option<String> {
    let mut root: Option<&str> = None;
    // A tarball also carries an entry for the root directory itself
    // ("llama-b10502/"), which has no second component. That is not a reason to
    // give up on flattening — but a *file* at the top level is.
    let mut has_nested = false;
    for name in names {
        let normalized = name.trim_start_matches("./").trim_end_matches('/');
        if normalized.is_empty() || normalized == "." {
            continue;
        }
        let (head, rest) = match normalized.split_once('/') {
            Some((h, r)) => {
                has_nested |= !r.is_empty();
                (h, r)
            }
            // A bare name: either the root dir's own entry, or a file that
            // proves the archive is flat. `strip_root` leaves it alone either
            // way, and the `has_nested` check below decides which it was.
            None => (normalized, ""),
        };
        // `..` must never be treated as a shared root: stripping it would
        // silently turn `../evil` into the innocent-looking `evil` and defeat
        // the traversal check downstream.
        if head.is_empty() || head == ".." || head == "." {
            return None;
        }
        let _ = rest;
        match root {
            None => root = Some(head),
            Some(r) if r == head => {}
            Some(_) => return None,
        }
    }
    root.filter(|_| has_nested).map(String::from)
}

/// Drop `root/` from the front of an archive-relative path.
fn strip_root(name: &str, root: &Option<String>) -> String {
    let name = name.trim_start_matches("./");
    match root {
        Some(r) => name
            .strip_prefix(r.as_str())
            .and_then(|rest| rest.strip_prefix('/'))
            .unwrap_or(name)
            .to_string(),
        None => name.to_string(),
    }
}

/// Reject an archive entry whose path escapes its destination (zip-slip /
/// tar-slip).
///
/// `zip::ZipFile::enclosed_name` does this for zips; `tar-rs` will happily
/// write `../`, so the same check has to be made by hand there. Called on the
/// **raw** entry name, before any root-flattening, so a hostile prefix cannot
/// be stripped into something that looks safe.
fn ensure_safe_rel(rel: &str) -> Result<(), String> {
    let rel_path = Path::new(rel);
    if rel_path.is_absolute()
        || rel_path
            .components()
            .any(|c| matches!(c, std::path::Component::ParentDir))
    {
        return Err(format!(
            "refusing archive: entry {rel} escapes the destination"
        ));
    }
    Ok(())
}

fn safe_join(dest: &Path, rel: &str) -> Result<PathBuf, String> {
    ensure_safe_rel(rel)?;
    let out = dest.join(Path::new(rel));
    if !out.starts_with(dest) {
        return Err(format!(
            "refusing archive: entry {rel} escapes the destination"
        ));
    }
    Ok(out)
}

fn open_tar(path: &Path) -> Result<tar::Archive<flate2::read::GzDecoder<std::fs::File>>, String> {
    let file = std::fs::File::open(path).map_err(|e| format!("open {}: {e}", path.display()))?;
    Ok(tar::Archive::new(flate2::read::GzDecoder::new(file)))
}

/// Extract `archive` into `dest`, flattening a single top-level directory.
///
/// Two passes over the gzip stream: gzip is not seekable, and re-inflating
/// ~35 MB is far cheaper than buffering the whole archive to learn its shape.
fn extract_tar_gz(archive: &Path, dest: &Path) -> Result<(), String> {
    let mut names = Vec::new();
    for entry in open_tar(archive)?
        .entries()
        .map_err(|e| format!("read {}: {e}", archive.display()))?
    {
        let entry = entry.map_err(|e| format!("read {}: {e}", archive.display()))?;
        let path = entry
            .path()
            .map_err(|e| format!("read {}: {e}", archive.display()))?;
        names.push(path.to_string_lossy().replace('\\', "/"));
    }
    let root = common_root(&names);

    for entry in open_tar(archive)?
        .entries()
        .map_err(|e| format!("read {}: {e}", archive.display()))?
    {
        let mut entry = entry.map_err(|e| format!("read {}: {e}", archive.display()))?;
        let name = entry
            .path()
            .map_err(|e| format!("read {}: {e}", archive.display()))?
            .to_string_lossy()
            .replace('\\', "/");
        ensure_safe_rel(&name)?;
        let rel = strip_root(&name, &root);
        if rel.is_empty() || rel == "." {
            continue;
        }
        let out = safe_join(dest, &rel)?;
        if entry.header().entry_type().is_dir() {
            std::fs::create_dir_all(&out).map_err(|e| format!("mkdir {}: {e}", out.display()))?;
            continue;
        }
        if let Some(parent) = out.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| format!("mkdir {}: {e}", parent.display()))?;
        }
        // unpack() restores the Unix mode, without which llama-server is not
        // executable. It also follows the header's own path, so it is given an
        // absolute destination we have already validated.
        entry
            .unpack(&out)
            .map_err(|e| format!("write {}: {e}", out.display()))?;
    }
    Ok(())
}

/// Extract `archive` into `dest`, flattening a single top-level directory.
fn extract_zip(archive: &Path, dest: &Path) -> Result<(), String> {
    let file =
        std::fs::File::open(archive).map_err(|e| format!("open {}: {e}", archive.display()))?;
    let mut zip =
        zip::ZipArchive::new(file).map_err(|e| format!("read {}: {e}", archive.display()))?;

    let mut names = Vec::with_capacity(zip.len());
    for i in 0..zip.len() {
        let entry = zip
            .by_index(i)
            .map_err(|e| format!("read zip entry {i}: {e}"))?;
        let Some(rel) = entry.enclosed_name() else {
            return Err(format!(
                "refusing archive: entry {} escapes the destination",
                entry.name()
            ));
        };
        names.push(rel.to_string_lossy().replace('\\', "/"));
    }
    let root = common_root(&names);

    for i in 0..zip.len() {
        let mut entry = zip
            .by_index(i)
            .map_err(|e| format!("read zip entry {i}: {e}"))?;
        let Some(rel) = entry.enclosed_name() else {
            return Err(format!(
                "refusing archive: entry {} escapes the destination",
                entry.name()
            ));
        };
        let raw = rel.to_string_lossy().replace('\\', "/");
        ensure_safe_rel(&raw)?;
        let rel = strip_root(&raw, &root);
        if rel.is_empty() || rel == "." {
            continue;
        }
        let out = safe_join(dest, &rel)?;

        if entry.is_dir() {
            std::fs::create_dir_all(&out).map_err(|e| format!("mkdir {}: {e}", out.display()))?;
            continue;
        }
        if let Some(parent) = out.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| format!("mkdir {}: {e}", parent.display()))?;
        }
        let mut writer =
            std::fs::File::create(&out).map_err(|e| format!("create {}: {e}", out.display()))?;
        std::io::copy(&mut entry, &mut writer)
            .map_err(|e| format!("write {}: {e}", out.display()))?;
        drop(writer);

        #[cfg(unix)]
        if let Some(mode) = entry.unix_mode() {
            use std::os::unix::fs::PermissionsExt;
            let _ = std::fs::set_permissions(&out, std::fs::Permissions::from_mode(mode));
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Regression, and the reason this predicate exists as a function at all:
    /// the sweep runs at every launch and deletes what it does not recognise,
    /// so a runtime missing from the list is erased between one session and the
    /// next. MTPLX was — 588 MB of interpreter and venv gone at startup, with
    /// the app then reporting it as not installed.
    #[test]
    fn every_runtime_this_build_installs_survives_the_sweep() {
        assert!(is_current_install(&format!("mlx-{MLX_VERSION}")));
        assert!(is_current_install(&format!("mtplx-{MTPLX_VERSION}")));
        assert!(is_current_install(&format!("{LLAMA_BUILD}-macos-arm64")));
    }

    #[test]
    fn an_older_version_of_any_runtime_is_swept() {
        assert!(!is_current_install("mlx-v0.0.1"));
        assert!(!is_current_install("mtplx-0.0.1"));
        assert!(!is_current_install("b1-macos-arm64"));
        // A bare runtime name with no version is not an install this build made.
        assert!(!is_current_install("mtplx"));
        assert!(!is_current_install("mlx"));
    }

    /// `mtplx-2.9.1` must not be kept alive by the `mlx-` comparison, nor the
    /// other way round: the two names share a prefix only if you squint, and a
    /// `starts_with` here would keep every stale MLX install forever.
    #[test]
    fn the_two_apple_runtimes_do_not_cover_for_each_other() {
        assert!(!is_current_install("mlx-2.9.1"));
        assert!(!is_current_install(&format!("mtplx-{MLX_VERSION}")));
    }

    use super::*;

    #[test]
    fn every_pinned_asset_has_a_plausible_hash_and_size() {
        assert!(!LLAMA_ASSETS.is_empty());
        for a in LLAMA_ASSETS {
            assert_eq!(a.sha256.len(), 64, "{} sha256 is not 64 hex", a.target);
            assert!(
                a.sha256.chars().all(|c| c.is_ascii_hexdigit()),
                "{} sha256 is not hex",
                a.target
            );
            // The smallest real asset (win-cpu-arm64) is >10 MB; a placeholder
            // is not.
            assert!(
                a.size > 5_000_000,
                "{} size {} looks like a placeholder",
                a.target,
                a.size
            );
        }
        let mut targets: Vec<_> = LLAMA_ASSETS.iter().map(|a| a.target).collect();
        targets.sort_unstable();
        let before = targets.len();
        targets.dedup();
        assert_eq!(before, targets.len(), "duplicate target in the pin table");
    }

    #[test]
    fn the_mlx_pin_is_a_plausible_release() {
        assert_eq!(MLX_SHA256.len(), 64);
        assert!(MLX_SHA256.chars().all(|c| c.is_ascii_hexdigit()));
        assert!(MLX_VERSION.starts_with('v'), "{MLX_VERSION}");
    }

    #[test]
    fn mlx_artifact_url_points_at_our_release() {
        let url = mlx_artifact_url();
        assert!(url.starts_with("https://github.com/claudin-io/claudinio-mlx/releases/download/"));
        assert!(url.ends_with("claudinio-mlx-macos-arm64.tar.gz"));
        assert!(url.contains(MLX_VERSION));
    }

    #[test]
    fn llama_build_looks_like_a_release_tag() {
        assert!(LLAMA_BUILD.starts_with('b'), "{LLAMA_BUILD}");
        assert!(LLAMA_BUILD[1..].chars().all(|c| c.is_ascii_digit()));
    }

    #[test]
    fn every_host_target_is_pinned() {
        for backend in [Backend::Auto, Backend::Cpu, Backend::Vulkan] {
            for target in host_targets(backend) {
                assert!(
                    asset_for(target).is_some(),
                    "host target {target} has no pinned asset"
                );
            }
        }
    }

    #[test]
    fn artifact_url_matches_the_github_release_layout() {
        assert_eq!(
            artifact_url("b10502", "macos-arm64").unwrap(),
            "https://github.com/ggml-org/llama.cpp/releases/download/\
             b10502/llama-b10502-bin-macos-arm64.tar.gz"
                .replace(' ', "")
        );
        assert_eq!(
            artifact_url("b10502", "win-vulkan-x64").unwrap(),
            "https://github.com/ggml-org/llama.cpp/releases/download/\
             b10502/llama-b10502-bin-win-vulkan-x64.zip"
                .replace(' ', "")
        );
        assert!(artifact_url("b10502", "not-a-target").is_none());
    }

    #[test]
    fn cpu_backend_never_resolves_to_a_vulkan_build() {
        for target in host_targets(Backend::Cpu) {
            assert!(!target.contains("vulkan"), "{target}");
        }
    }

    #[test]
    fn common_root_flattens_the_tag_directory() {
        let nested = vec![
            "llama-b10502/llama-server".to_string(),
            "llama-b10502/libllama.dylib".to_string(),
        ];
        assert_eq!(common_root(&nested).as_deref(), Some("llama-b10502"));
        let root = common_root(&nested);
        assert_eq!(strip_root(&nested[0], &root), "llama-server");
    }

    /// The real tarball shape: a root directory entry, then everything under
    /// it. Missing this is what left llama-server one level too deep the first
    /// time round.
    #[test]
    fn common_root_ignores_the_roots_own_directory_entry() {
        let names = vec![
            "llama-b10502/".to_string(),
            "llama-b10502/llama-server".to_string(),
            "llama-b10502/libggml.dylib".to_string(),
        ];
        assert_eq!(common_root(&names).as_deref(), Some("llama-b10502"));
    }

    #[test]
    fn common_root_handles_the_dot_slash_prefix_tar_emits() {
        let names = vec![
            "./llama-b10502/llama-server".to_string(),
            "./llama-b10502/libggml.dylib".to_string(),
        ];
        let root = common_root(&names);
        assert_eq!(root.as_deref(), Some("llama-b10502"));
        assert_eq!(strip_root(&names[0], &root), "llama-server");
    }

    /// A single top-level directory alongside a top-level file is not a
    /// wrapper, and flattening it would drop that file on top of the tree.
    #[test]
    fn common_root_refuses_when_a_file_sits_at_the_top_level() {
        let names = vec!["llama-server".to_string(), "libggml.dylib".to_string()];
        assert_eq!(common_root(&names), None);
    }

    #[test]
    fn common_root_leaves_a_flat_archive_alone() {
        let flat = vec![
            "llama-server.exe".to_string(),
            "ggml-vulkan.dll".to_string(),
        ];
        assert_eq!(common_root(&flat), None);
        assert_eq!(strip_root(&flat[0], &None), "llama-server.exe");
    }

    #[test]
    fn common_root_leaves_a_two_root_archive_alone() {
        let two = vec!["a/one".to_string(), "b/two".to_string()];
        assert_eq!(common_root(&two), None);
    }

    #[test]
    fn safe_join_rejects_traversal() {
        let dest = Path::new("/tmp/claudinio-test");
        assert!(safe_join(dest, "../evil").is_err());
        assert!(safe_join(dest, "nested/../../evil").is_err());
        assert!(safe_join(dest, "llama-server").is_ok());
    }

    /// Regression: `..` shares a "root" with nothing, and treating it as one
    /// would strip the traversal away before it could be rejected.
    #[test]
    fn common_root_never_treats_parent_dir_as_a_root() {
        let evil = vec!["../evil".to_string()];
        assert_eq!(common_root(&evil), None);
        let mixed = vec!["../evil".to_string(), "../other".to_string()];
        assert_eq!(common_root(&mixed), None);
    }

    #[test]
    fn extract_tar_gz_rejects_a_traversing_entry() {
        use std::io::Write;
        let tmp = tempfile::tempdir().unwrap();
        let archive = tmp.path().join("evil.tar.gz");
        {
            let file = std::fs::File::create(&archive).unwrap();
            let enc = flate2::write::GzEncoder::new(file, flate2::Compression::fast());
            let mut builder = tar::Builder::new(enc);
            let payload = b"pwned";
            let mut header = tar::Header::new_gnu();
            header.set_size(payload.len() as u64);
            header.set_mode(0o644);
            // `set_path`/`append_data` refuse to write a `..` component, so
            // the name is planted straight into the header bytes — which is
            // exactly what a hostile archive off the network would contain.
            let name = b"../evil";
            header.as_old_mut().name[..name.len()].copy_from_slice(name);
            header.set_cksum();
            builder.append(&header, &payload[..]).unwrap();
            let mut enc = builder.into_inner().unwrap();
            enc.flush().unwrap();
            enc.finish().unwrap();
        }
        let dest = tmp.path().join("out");
        std::fs::create_dir_all(&dest).unwrap();
        assert!(extract_tar_gz(&archive, &dest).is_err());
        assert!(!tmp.path().join("evil").exists());
    }

    #[test]
    fn extract_tar_gz_flattens_the_tag_directory() {
        use std::io::Write;
        let tmp = tempfile::tempdir().unwrap();
        let archive = tmp.path().join("llama.tar.gz");
        {
            let file = std::fs::File::create(&archive).unwrap();
            let enc = flate2::write::GzEncoder::new(file, flate2::Compression::fast());
            let mut builder = tar::Builder::new(enc);
            for name in ["llama-b1/llama-server", "llama-b1/libllama.dylib"] {
                let payload = b"binary";
                let mut header = tar::Header::new_gnu();
                header.set_size(payload.len() as u64);
                header.set_mode(0o755);
                header.set_cksum();
                builder
                    .append_data(&mut header, name, &payload[..])
                    .unwrap();
            }
            let mut enc = builder.into_inner().unwrap();
            enc.flush().unwrap();
            enc.finish().unwrap();
        }
        let dest = tmp.path().join("out");
        extract_tar_gz(&archive, &dest).unwrap();
        assert!(dest.join("llama-server").is_file());
        assert!(dest.join("libllama.dylib").is_file());
        assert!(!dest.join("llama-b1").exists());
    }

    /// Windows MAX_PATH is why the install dir is `<build>-<target>` and not
    /// the full asset name.
    #[test]
    fn install_dir_leaf_is_short_and_flat() {
        let dir = install_dir("macos-arm64").unwrap();
        let leaf = dir.file_name().unwrap().to_str().unwrap();
        assert!(!leaf.contains('/') && !leaf.contains('\\'), "{leaf}");
        assert!(leaf.len() <= 32, "{leaf} is {} chars", leaf.len());
    }
}
