// GENERATED by scripts/pin_chromium.py — do not hand-edit.
pub const CHROMIUM_VERSION: &str = "151.0.7922.77";

pub const CHROMIUM_BUILDS: &[ChromiumBuild] = &[
    ChromiumBuild {
        platform: "mac-arm64",
        sha256: "4b3caaabb967070f1541ff5b0fd2c95b2ba839be33a58842a8a877ec5f3fbd9b",
        size: 187103225,
        exe_in_zip: "chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing",
    },
    ChromiumBuild {
        platform: "mac-x64",
        sha256: "0345f09aaa36c85cf716959390f8a7d73b22fe4a26c1e7735dcb5653e474887a",
        size: 197089530,
        exe_in_zip: "chrome-mac-x64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing",
    },
    ChromiumBuild {
        platform: "win64",
        sha256: "a561db084cf08f3f4d25681ed3e764726b0537082f27063848a01e2e23d612ae",
        size: 201082655,
        exe_in_zip: "chrome-win64/chrome.exe",
    },
    ChromiumBuild {
        platform: "linux64",
        sha256: "60a324a6e1d27b20f2035a2cdaf71641a739fe1f5571f63794773225820bce8a",
        size: 193276481,
        exe_in_zip: "chrome-linux64/chrome",
    },
];
