//! Getting a Chromium onto disk.
//!
//! The agent drives a **dedicated** browser, never the user's own Chrome and
//! never their profile: a profile holds live session cookies for their bank,
//! email and GitHub, and an agent with those plus one hostile page is credential
//! exfiltration. So this module fetches a pinned Chrome for Testing build and
//! keeps it under the app's data dir.
//!
//! Chrome for Testing publishes immutable per-version URLs but no checksums, so
//! the hashes below are computed by `scripts/pin_chromium.py` and committed —
//! same arrangement as the embedding model in `code_intel::embeddings`.

use crate::download::{DEFAULT_RETRIES, ProgressFn, download_verified_with_retries};
use crate::net_activity::NetSource;
use std::path::{Path, PathBuf};

pub struct ChromiumBuild {
    pub platform: &'static str,
    pub sha256: &'static str,
    pub size: u64,
    /// Path of the executable inside the zip.
    pub exe_in_zip: &'static str,
}

// GENERATED by scripts/pin_chromium.py — do not hand-edit.
//
// When bumping this, re-run the golden-pixel screenshot test: the exact
// semantics of `Page.captureScreenshot`'s `clip` combined with
// `captureBeyondViewport` have changed between Chrome versions before, and the
// element/region capture math is calibrated against a known-good build.
include!("chromium_pins.rs");

const BASE_URL: &str = "https://storage.googleapis.com/chrome-for-testing-public";

/// Marker written only after a complete extraction, so a crash mid-unzip can
/// never leave a half-populated directory that looks installed.
const READY_MARKER: &str = ".ready";

/// The Chrome for Testing platform string for the host, or `None` on a target
/// they do not publish (32-bit, or a BSD).
pub fn host_platform() -> Option<&'static str> {
    match (std::env::consts::OS, std::env::consts::ARCH) {
        ("macos", "aarch64") => Some("mac-arm64"),
        ("macos", "x86_64") => Some("mac-x64"),
        ("windows", "x86_64") => Some("win64"),
        ("linux", "x86_64") => Some("linux64"),
        _ => None,
    }
}

pub fn build_for(platform: &str) -> Option<&'static ChromiumBuild> {
    CHROMIUM_BUILDS.iter().find(|b| b.platform == platform)
}

pub fn artifact_url(version: &str, platform: &str) -> String {
    format!("{BASE_URL}/{version}/{platform}/chrome-{platform}.zip")
}

/// Root for everything this module owns, under the machine-local app data dir.
///
/// Never inside the workspace: Chromium mmaps LevelDB files in its profile, and
/// on an SMB share that corrupts or hangs — the same lesson already recorded for
/// the index database.
pub fn browser_dir() -> Result<PathBuf, String> {
    let base = dirs::data_dir().ok_or_else(|| "no data directory on this platform".to_string())?;
    Ok(base.join("claudinio-code").join("browser"))
}

/// Install directory for the pinned build.
///
/// Deliberately short (`browser/141/`, not
/// `browser/chrome-141.0.7390.54-win64/`): the executable sits several levels
/// deep inside the archive, and on Windows the combined path has to stay under
/// MAX_PATH.
pub fn install_dir() -> Result<PathBuf, String> {
    let major = CHROMIUM_VERSION
        .split('.')
        .next()
        .unwrap_or(CHROMIUM_VERSION);
    Ok(browser_dir()?.join(major))
}

/// Absolute path of the managed executable, whether or not it exists yet.
pub fn managed_exe() -> Result<PathBuf, String> {
    let platform = host_platform().ok_or_else(|| {
        format!(
            "no Chrome for Testing build for {}-{}",
            std::env::consts::OS,
            std::env::consts::ARCH
        )
    })?;
    let build = build_for(platform)
        .ok_or_else(|| format!("no pinned Chromium for platform '{platform}'"))?;
    Ok(install_dir()?.join(build.exe_in_zip))
}

pub fn is_installed() -> bool {
    match (install_dir(), managed_exe()) {
        (Ok(dir), Ok(exe)) => dir.join(READY_MARKER).exists() && exe.exists(),
        _ => false,
    }
}

/// Download and extract the pinned Chromium if it is not already installed.
///
/// Callers must have user consent before reaching here: this pulls ~170 MB over
/// the user's connection, which is not something a tool call may do silently.
pub async fn ensure_installed(on_progress: Option<&ProgressFn>) -> Result<PathBuf, String> {
    let exe = managed_exe()?;
    if is_installed() {
        return Ok(exe);
    }
    let platform = host_platform().expect("managed_exe would have failed first");
    let build = build_for(platform).expect("managed_exe would have failed first");

    let dir = install_dir()?;
    // A previous attempt may have died mid-extract; start clean rather than
    // unzipping over the wreckage.
    if dir.exists() {
        std::fs::remove_dir_all(&dir).map_err(|e| format!("clear {}: {e}", dir.display()))?;
    }
    std::fs::create_dir_all(&dir).map_err(|e| format!("create {}: {e}", dir.display()))?;

    let zip_path = browser_dir()?.join(format!("chrome-{platform}.zip"));
    let label = format!("Chromium {CHROMIUM_VERSION} ({platform})");
    download_verified_with_retries(
        &artifact_url(CHROMIUM_VERSION, platform),
        &zip_path,
        &label,
        build.sha256,
        build.size,
        NetSource::ChromiumDownload,
        on_progress,
        DEFAULT_RETRIES,
    )
    .await?;

    let extract_dir = dir.clone();
    let zip_for_task = zip_path.clone();
    // Unzipping ~400 MB is blocking CPU and file I/O; keeping it on an async
    // worker would stall every other task on the runtime.
    tokio::task::spawn_blocking(move || extract_zip(&zip_for_task, &extract_dir))
        .await
        .map_err(|e| format!("extract task failed: {e}"))??;

    let _ = std::fs::remove_file(&zip_path);

    if !exe.exists() {
        return Err(format!(
            "extracted archive is missing the expected executable at {}",
            build.exe_in_zip
        ));
    }
    std::fs::write(dir.join(READY_MARKER), CHROMIUM_VERSION)
        .map_err(|e| format!("write ready marker: {e}"))?;
    Ok(exe)
}

/// Remove the managed install (binary and ready marker), leaving profiles alone.
pub fn uninstall() -> Result<(), String> {
    let dir = install_dir()?;
    if dir.exists() {
        std::fs::remove_dir_all(&dir).map_err(|e| format!("remove {}: {e}", dir.display()))?;
    }
    Ok(())
}

/// Extract `zip_path` into `dest`.
///
/// Rejects entries whose path escapes `dest` (zip-slip) and restores the Unix
/// mode, without which the extracted binary is not executable.
fn extract_zip(zip_path: &Path, dest: &Path) -> Result<(), String> {
    let file =
        std::fs::File::open(zip_path).map_err(|e| format!("open {}: {e}", zip_path.display()))?;
    let mut archive =
        zip::ZipArchive::new(file).map_err(|e| format!("read {}: {e}", zip_path.display()))?;

    for i in 0..archive.len() {
        let mut entry = archive
            .by_index(i)
            .map_err(|e| format!("read zip entry {i}: {e}"))?;
        let Some(rel) = entry.enclosed_name() else {
            return Err(format!(
                "refusing archive: entry {} escapes the destination",
                entry.name()
            ));
        };
        let out = dest.join(&rel);
        // enclosed_name() already rejects traversal, but the archive is a
        // remote artifact and the cost of checking twice is nothing.
        if !out.starts_with(dest) {
            return Err(format!("refusing archive: entry {} escapes", entry.name()));
        }

        if entry.is_dir() {
            std::fs::create_dir_all(&out).map_err(|e| format!("mkdir {}: {e}", out.display()))?;
            continue;
        }
        if let Some(parent) = out.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| format!("mkdir {}: {e}", parent.display()))?;
        }
        let mut writer =
            std::fs::File::create(&out).map_err(|e| format!("create {}: {e}", out.display()))?;
        std::io::copy(&mut entry, &mut writer)
            .map_err(|e| format!("write {}: {e}", out.display()))?;
        drop(writer);

        #[cfg(unix)]
        if let Some(mode) = entry.unix_mode() {
            use std::os::unix::fs::PermissionsExt;
            let _ = std::fs::set_permissions(&out, std::fs::Permissions::from_mode(mode));
        }
    }
    Ok(())
}

/// Paths where a user-installed Chrome-family browser normally lives.
///
/// Offered as an alternative to the ~170 MB download. Even when one is chosen,
/// it is still launched as a fresh process against our own `--user-data-dir`;
/// the user's profile is never touched.
pub fn detect_system_chrome() -> Option<PathBuf> {
    let candidates: &[&str] = match std::env::consts::OS {
        "macos" => &[
            "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
            "/Applications/Chromium.app/Contents/MacOS/Chromium",
            "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
        ],
        "windows" => &[
            r"C:\Program Files\Google\Chrome\Application\chrome.exe",
            r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
            r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
        ],
        "linux" => &[
            "/usr/bin/google-chrome",
            "/usr/bin/google-chrome-stable",
            "/usr/bin/chromium",
            "/usr/bin/chromium-browser",
            "/usr/bin/microsoft-edge",
        ],
        _ => &[],
    };
    candidates.iter().map(PathBuf::from).find(|p| p.exists())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_pinned_platform_has_a_plausible_hash_and_size() {
        assert_eq!(CHROMIUM_BUILDS.len(), 4);
        for b in CHROMIUM_BUILDS {
            assert_eq!(b.sha256.len(), 64, "{} sha256 is not 64 hex", b.platform);
            assert!(
                b.sha256.chars().all(|c| c.is_ascii_hexdigit()),
                "{} sha256 is not hex",
                b.platform
            );
            // Every real Chrome for Testing zip is >100 MB; a placeholder is not.
            assert!(
                b.size > 100_000_000,
                "{} size {} looks like a placeholder",
                b.platform,
                b.size
            );
            assert!(!b.exe_in_zip.is_empty());
        }
    }

    #[test]
    fn artifact_url_matches_the_chrome_for_testing_layout() {
        assert_eq!(
            artifact_url("141.0.0.1", "mac-arm64"),
            "https://storage.googleapis.com/chrome-for-testing-public/\
             141.0.0.1/mac-arm64/chrome-mac-arm64.zip"
                .replace(' ', "")
        );
    }

    #[test]
    fn host_platform_resolves_to_a_pinned_build_on_supported_targets() {
        if let Some(p) = host_platform() {
            assert!(
                build_for(p).is_some(),
                "host platform {p} has no pinned build"
            );
        }
    }

    /// Windows MAX_PATH is the reason the install dir is the bare major
    /// version. `%LOCALAPPDATA%` plus the in-archive path already runs long.
    #[test]
    fn install_dir_is_named_by_major_version_only() {
        let dir = install_dir().unwrap();
        let leaf = dir.file_name().unwrap().to_str().unwrap();
        assert!(
            leaf.chars().all(|c| c.is_ascii_digit()),
            "install dir leaf {leaf:?} should be just the major version"
        );
    }
}
