// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who answered an approval gate.
 */
export type Actor = { "kind": "local" } | { "kind": "peer", "label": string } | { "kind": "expired" };
