// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Attachment = { name: string, media_type: string, 
/**
 * Base64. Size is bounded by `MAX_FRAME` on the way out.
 */
data: string, };
