// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why the device stopped serving.
 */
export type CloseReason = "peer_asked" | "turned_off_locally" | "grant_expired" | "revoked";
