// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Actor } from "./Actor";
import type { Decision } from "./Decision";
import type { Policy } from "./Policy";
import type { JsonValue } from "./serde_json/JsonValue";

export type DeviceToPeer = { "kind": "snapshot", session_id: string, records: Array<JsonValue>, seq: bigint, } | { "kind": "event", session_id: string, seq: bigint, event: JsonValue, } | { "kind": "approval_request", session_id: string, tool_use_id: string, tool: string, args: JsonValue, diff?: string | null, 
/**
 * Unix millis. An approval nobody answers must not hang forever.
 */
expires_at: bigint, } | { "kind": "approval_resolved", tool_use_id: string, decision: Decision, actor: Actor, } | { "kind": "gap", session_id: string, from_seq: bigint, to_seq: bigint, } | { "kind": "policy_denied", cmd_id: string, rule: string, human_reason: string, } | { "kind": "policy" } & Policy | { "kind": "ack", cmd_id: string, } | { "kind": "error", cmd_id: string, code: string, message: string, };
