// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attachment } from "./Attachment";
import type { Decision } from "./Decision";

export type PeerToDevice = { "kind": "list_workspaces" } | { "kind": "list_sessions", workspace: string, } | { "kind": "subscribe", session_id: string, from_seq: bigint, } | { "kind": "unsubscribe", session_id: string, } | { "kind": "send_message", cmd_id: string, session_id: string, text: string, attachments?: Array<Attachment>, } | { "kind": "steer", cmd_id: string, session_id: string, text: string, } | { "kind": "interrupt", cmd_id: string, session_id: string, } | { "kind": "resolve_approval", cmd_id: string, session_id: string, tool_use_id: string, decision: Decision, reason?: string | null, } | { "kind": "set_mode", cmd_id: string, session_id: string, mode: string, } | { "kind": "get_policy" } | { "kind": "end_remote" };
