// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BashApproval } from "./BashApproval";

/**
 * What a peer is allowed to do, as the device sees it.
 *
 * Sent to the peer for display only. The device enforces; the peer is told so
 * its UI can be honest about what is available.
 */
export type Policy = { send_message: boolean, steer: boolean, interrupt: boolean, set_mode: boolean, approve_edit: boolean, approve_bash: BashApproval, read_attachment: boolean, export_file: boolean, 
/**
 * Unix millis after which every grant lapses.
 */
expires_at?: bigint | null, };
