#!/usr/bin/env python3
"""Compute the pinned llama.cpp table for src-tauri/src/llama/llama_pins.rs.

The GitHub Releases API publishes immutable per-tag asset URLs and a size, but
no checksum, so we hash the artifacts ourselves and commit the result — the
same arrangement as Chrome for Testing in pin_chromium.py and the embedding
model in fetch_embedding_model.py.

    python3 scripts/pin_llama.py           # latest release
    python3 scripts/pin_llama.py b10502

Prints a Rust literal to redirect into src-tauri/src/llama/llama_pins.rs.
Streams each artifact and hashes it without keeping it on disk (11-35 MB per
target, 9 targets). Stdlib only.

After bumping the pin, run the Local models -> Test button against an already
installed model: a llama-server can reject a GGUF produced by a newer one, and
that is the only way the mismatch surfaces.
"""

import hashlib
import json
import sys
import urllib.request

LATEST = "https://api.github.com/repos/ggml-org/llama.cpp/releases/latest"
BY_TAG = "https://api.github.com/repos/ggml-org/llama.cpp/releases/tags/{tag}"

# target -> archive kind. The target is the substring between "bin-" and the
# extension in the asset name, and is also the leaf of the install directory.
#
# CUDA/ROCm/SYCL/OpenVINO are deliberately absent: those builds need a second
# runtime archive (cudart-*.zip is ~390 MB) unpacked into the same directory,
# which doubles both this table and the ways an install can be half-broken.
# Vulkan covers NVIDIA, AMD and Intel on Windows and Linux.
TARGETS = {
    "macos-arm64": "TarGz",
    "macos-x64": "TarGz",
    "ubuntu-x64": "TarGz",
    "ubuntu-vulkan-x64": "TarGz",
    "ubuntu-arm64": "TarGz",
    "ubuntu-vulkan-arm64": "TarGz",
    "win-cpu-x64": "Zip",
    "win-vulkan-x64": "Zip",
    "win-cpu-arm64": "Zip",
}


def fetch_release(tag: str | None) -> dict:
    url = LATEST if tag is None else BY_TAG.format(tag=tag)
    req = urllib.request.Request(url, headers={"Accept": "application/vnd.github+json"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.load(r)


def asset_name(tag: str, target: str, kind: str) -> str:
    ext = "tar.gz" if kind == "TarGz" else "zip"
    return f"llama-{tag}-bin-{target}.{ext}"


def hash_asset(url: str, label: str) -> tuple[str, int]:
    digest = hashlib.sha256()
    size = 0
    with urllib.request.urlopen(url, timeout=600) as r:
        while chunk := r.read(1 << 20):
            digest.update(chunk)
            size += len(chunk)
            print(f"  {label}: {size / 1e6:7.1f} MB", end="\r", file=sys.stderr)
    print(f"  {label}: {size / 1e6:7.1f} MB  done", file=sys.stderr)
    return digest.hexdigest(), size


def main() -> int:
    tag = sys.argv[1] if len(sys.argv) > 1 else None
    release = fetch_release(tag)
    tag = release["tag_name"]
    print(f"llama.cpp {tag}", file=sys.stderr)

    by_name = {a["name"]: a for a in release["assets"]}
    rows = []
    for target, kind in TARGETS.items():
        name = asset_name(tag, target, kind)
        asset = by_name.get(name)
        if asset is None:
            print(f"  {target}: MISSING ({name})", file=sys.stderr)
            return 1
        sha, size = hash_asset(asset["browser_download_url"], target)
        if size != asset["size"]:
            print(
                f"  {target}: size mismatch, API said {asset['size']}, got {size}",
                file=sys.stderr,
            )
            return 1
        rows.append((target, kind, sha, size))

    print("// GENERATED by scripts/pin_llama.py — do not hand-edit.")
    print("//")
    print("// Regenerate with:")
    print("//   python3 scripts/pin_llama.py > src-tauri/src/llama/llama_pins.rs")
    print()
    print(f'pub const LLAMA_BUILD: &str = "{tag}";')
    print()
    print("pub const LLAMA_ASSETS: &[LlamaAsset] = &[")
    for target, kind, sha, size in rows:
        print("    LlamaAsset {")
        print(f'        target: "{target}",')
        print(f"        archive: Archive::{kind},")
        print(f'        sha256: "{sha}",')
        print(f"        size: {size},")
        print("    },")
    print("];")
    return 0


if __name__ == "__main__":
    sys.exit(main())
