#!/usr/bin/env python3
"""Compute the pinned claudinio-mlx table for src-tauri/src/llama/mlx_pins.rs.

The MLX engine is our own sidecar (github.com/claudin-io/claudinio-mlx), built
on Apple's mlx-swift. It is pinned by version + sha256 exactly like the upstream
llama.cpp binaries: being our own artifact is not a reason to trust the network
it arrives over.

    python3 scripts/pin_mlx.py            # latest release
    python3 scripts/pin_mlx.py v0.1.0

Prints a Rust literal to redirect into src-tauri/src/llama/mlx_pins.rs.
Stdlib only.
"""

import hashlib
import json
import sys
import urllib.request

REPO = "claudin-io/claudinio-mlx"
LATEST = f"https://api.github.com/repos/{REPO}/releases/latest"
BY_TAG = f"https://api.github.com/repos/{REPO}/releases/tags/{{tag}}"

# Apple Silicon only: MLX is Metal, and there is nothing to build for anything
# else. A user on another platform never sees the engine offered.
ASSET = "claudinio-mlx-macos-arm64.tar.gz"


def fetch_release(tag: str | None) -> dict:
    url = LATEST if tag is None else BY_TAG.format(tag=tag)
    req = urllib.request.Request(url, headers={"Accept": "application/vnd.github+json"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.load(r)


def hash_asset(url: str) -> tuple[str, int]:
    digest = hashlib.sha256()
    size = 0
    with urllib.request.urlopen(url, timeout=600) as r:
        while chunk := r.read(1 << 20):
            digest.update(chunk)
            size += len(chunk)
            print(f"  {size / 1e6:7.1f} MB", end="\r", file=sys.stderr)
    print(f"  {size / 1e6:7.1f} MB  done", file=sys.stderr)
    return digest.hexdigest(), size


def main() -> int:
    tag = sys.argv[1] if len(sys.argv) > 1 else None
    release = fetch_release(tag)
    tag = release["tag_name"]
    print(f"claudinio-mlx {tag}", file=sys.stderr)

    asset = next((a for a in release["assets"] if a["name"] == ASSET), None)
    if asset is None:
        print(f"  MISSING asset {ASSET}", file=sys.stderr)
        return 1

    sha, size = hash_asset(asset["browser_download_url"])
    if size != asset["size"]:
        print(f"  size mismatch: API said {asset['size']}, got {size}", file=sys.stderr)
        return 1

    print("// GENERATED by scripts/pin_mlx.py — do not hand-edit.")
    print("//")
    print("// Regenerate with:")
    print("//   python3 scripts/pin_mlx.py > src-tauri/src/llama/mlx_pins.rs")
    print()
    print(f'pub const MLX_VERSION: &str = "{tag}";')
    print(f'pub const MLX_SHA256: &str = "{sha}";')
    print(f"pub const MLX_SIZE: u64 = {size};")
    return 0


if __name__ == "__main__":
    sys.exit(main())
