#!/usr/bin/env python3
"""Compute the pinned MTPLX table for src-tauri/src/llama/mtplx_pins.rs.

MTPLX (github.com/youssofal/MTPLX, Apache-2.0) is the only engine here that is
a Python package rather than a binary. Two things therefore have to be pinned
instead of one:

  - the interpreter, because the app must not depend on whichever python3 a
    user happens to have. macOS ships 3.9 and MTPLX needs 3.11+, so on a Mac
    without Homebrew there is no usable interpreter at all. A standalone build
    from astral-sh/python-build-standalone is 25 MB, carries a sha256, and
    makes every install identical — which is the difference between a bug that
    reproduces and one that only happens on someone else's machine.

  - the MTPLX version, so an install today and an install next month serve the
    same engine.

    python3 scripts/pin_mtplx.py            # newest standalone + newest mtplx
    python3 scripts/pin_mtplx.py 2.9.1      # a specific mtplx version

Prints a Rust literal to redirect into src-tauri/src/llama/mtplx_pins.rs.
Stdlib only.
"""

import hashlib
import json
import sys
import urllib.request

PBS = "https://api.github.com/repos/astral-sh/python-build-standalone/releases/latest"
PYPI = "https://pypi.org/pypi/mtplx/json"

# Apple Silicon only: MTPLX is MLX, which is Metal. `install_only` is the
# runtime layout (bin/python3, lib/) rather than the build tree.
PY_MINOR = "3.12"
PY_ASSET_MARK = "aarch64-apple-darwin-install_only.tar.gz"


def fetch(url: str) -> dict:
    req = urllib.request.Request(url, headers={"Accept": "application/json"})
    with urllib.request.urlopen(req) as r:
        return json.load(r)


def sha256_of(url: str) -> tuple[str, int]:
    digest = hashlib.sha256()
    size = 0
    with urllib.request.urlopen(url) as r:
        while chunk := r.read(1 << 20):
            digest.update(chunk)
            size += len(chunk)
    return digest.hexdigest(), size


def main() -> None:
    release = fetch(PBS)
    asset = next(
        (
            a
            for a in release["assets"]
            if a["name"].endswith(PY_ASSET_MARK) and PY_MINOR in a["name"]
        ),
        None,
    )
    if asset is None:
        sys.exit(f"no {PY_MINOR} {PY_ASSET_MARK} asset in {release['tag_name']}")

    print(f"downloading {asset['name']}...", file=sys.stderr)
    py_sha, py_size = sha256_of(asset["browser_download_url"])
    # cpython-3.12.14+20260814-aarch64-... -> 3.12.14+20260814
    py_version = asset["name"].split("-")[1]

    want = sys.argv[1] if len(sys.argv) > 1 else None
    mtplx_version = want or fetch(PYPI)["info"]["version"]

    print(f"""// GENERATED by scripts/pin_mtplx.py — do not hand-edit.
//
// Regenerate with:
//   python3 scripts/pin_mtplx.py > src-tauri/src/llama/mtplx_pins.rs

/// The interpreter the MTPLX venv is built on. Bundled rather than borrowed:
/// macOS ships Python 3.9 and MTPLX needs 3.11+, so "use the system python"
/// means "does not install" on any Mac without Homebrew.
pub const PYTHON_VERSION: &str = "{py_version}";
pub const PYTHON_URL: &str = "{asset['browser_download_url']}";
pub const PYTHON_SHA256: &str = "{py_sha}";
pub const PYTHON_SIZE: u64 = {py_size};

/// The MTPLX release to install into that venv.
pub const MTPLX_VERSION: &str = "{mtplx_version}";""")


if __name__ == "__main__":
    main()
